/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as LojaIdRouteImport } from './routes/loja.$id'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIdRoute = LojaIdRouteImport.update({
  id: '/loja/$id',
  path: '/loja/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categorias': typeof CategoriasRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$id': typeof LojaIdRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categorias': typeof CategoriasRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$id': typeof LojaIdRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categorias': typeof CategoriasRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$id': typeof LojaIdRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/categorias'
    | '/categoria/$slug'
    | '/loja/$id'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/categorias'
    | '/categoria/$slug'
    | '/loja/$id'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/categorias'
    | '/categoria/$slug'
    | '/loja/$id'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CategoriasRoute: typeof CategoriasRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  LojaIdRoute: typeof LojaIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$id': {
      id: '/loja/$id'
      path: '/loja/$id'
      fullPath: '/loja/$id'
      preLoaderRoute: typeof LojaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CategoriasRoute: CategoriasRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  LojaIdRoute: LojaIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
